INSERT INTO TAGS(NAME) VALUES('sport');
INSERT INTO TAGS(NAME) VALUES('Java');
INSERT INTO TAGS(NAME) VALUES('skilled');
INSERT INTO TAGS(NAME) VALUES('smart');
INSERT INTO TAGS(NAME) VALUES('trashtalk');

INSERT INTO PERSONS(FIO, DEVELOPER, EMAIL, HOBBIES) VALUES('Bobunov', 'Java', 'jom.everest@gmail.com', 'football');
INSERT INTO PERSONS(FIO, DEVELOPER, EMAIL, HOBBIES) VALUES('Martin', 'Python', 'martin@gmail.com', 'golf');

INSERT INTO PERSON_TAG(PERSON_ID, TAG) VALUES('1', 'Java');
INSERT INTO PERSON_TAG(PERSON_ID, TAG) VALUES('1', 'skilled');
INSERT INTO PERSON_TAG(PERSON_ID, TAG) VALUES('2', 'sport');
INSERT INTO PERSON_TAG(PERSON_ID, TAG) VALUES('2', 'Java');